using Spider.Network;
using System.Text;
using Spider.Data;

namespace AsyncSocketHost
{
    class TestCommand : CommandBase
    {
        private string message = @"1hddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksadkssssssssssssssssssssssssssssssssssssssssssssssssssssssssss;adkapdqdqdopkokdkokodoopdokpkopqdkoqokdkoqkodokq
ddddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigdqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksddewiigwgewifuiufguiuiuhiuhhwiowihiiwdwwwwwwwwww
dqdqqhkqdksi119";
        public override string Name
        {
            get
            {
                return "test";
            }
        }

        public override byte[] Process(SmartObject data)
        {
            //throw new Exception("error");
            return Encoding.UTF8.GetBytes(message);
        }
    }
}
